# Generated by Django 4.2.2 on 2023-10-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='quantity_available',
            new_name='quantity_available_lbs',
        ),
    ]
